version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lms-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - lms-network

volumes:
  postgres-data:

networks:
  lms-network: